# Generated by Django 4.2.1 on 2023-06-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('Codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.categoria', verbose_name='Producto')),
            ],
        ),
    ]
