# Generated by Django 4.2.1 on 2023-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_producto_delete_alimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
